version: '3.2'

services:
  www:
    build: .
    environment:
      NODE_ENV: productiony
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foster-dla.rule=Host(`donate.dimonalovesanimals.org`)"
      - "traefik.http.routers.foster-dla.entrypoints=websecure"
      - "traefik.http.routers.foster-dla.tls.certresolver=myresolver"
