version: '3.2'

services:
  www:
    restart: unless-stopped
    build: .
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.donate-dla.rule=Host(`donate.dimonalovesanimals.org`)"
      - "traefik.http.routers.donate-dla.entrypoints=websecure"
      - "traefik.http.routers.donate-dla.tls.certresolver=myresolver"
